"""create_profiles_table

Revision ID: 32a6ac698126
Revises: 25121b287d3d
Create Date: 2026-09-30 13:51:12.794228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a6ac698126'
down_revision: Union[str, Sequence[str], None] = '25121b287d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False, comment='male | female | other'),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False, comment='ISO 639-1 language code: en, hi, es, etc.'),
    sa.Column('bio', sa.Text(), nullable=True, comment='Optional short bio shown to match partner.'),
    sa.Column('is_complete', sa.Boolean(), nullable=False, comment='True once the user finishes the full onboarding flow.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
