"""create_search_preferences_table

Revision ID: cdb6160795aa
Revises: 32a6ac698126
Create Date: 2026-09-30 14:25:36.103772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb6160795aa'
down_revision: Union[str, Sequence[str], None] = '32a6ac698126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('preferred_gender', sa.String(length=20), nullable=False, comment='any | male | female | other — what gender partner do they want?'),
    sa.Column('preferred_age_min', sa.Integer(), nullable=False, comment='Minimum partner age (inclusive).'),
    sa.Column('preferred_age_max', sa.Integer(), nullable=False, comment='Maximum partner age (inclusive).'),
    sa.Column('preferred_language', sa.String(length=10), nullable=False, comment='any | en | hi | es | ... — filter partners by language.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='If False, user is excluded from matchmaking entirely.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_preferences_user_id'), 'search_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_preferences_user_id'), table_name='search_preferences')
    op.drop_table('search_preferences')
    # ### end Alembic commands ###
